name: github-auto-commit
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: "30 6 * * *"


jobs:
  auto commit to github:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: command line
        run:
          git config --local user.email tisou1@qq.com
          git config --local user.name tisou1
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push

